# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\StarGear\Desktop\Mona 30 - New\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.



from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.keys import Keys
import time
from selenium.webdriver import ActionChains
import random
import re

def bot():

   # Đăng nhập bot số 1
   driver = webdriver.Chrome()
   driver.maximize_window()
   driver.get('https://discord.com/login')
   time.sleep(1)
   driver.find_element_by_name('email').send_keys(open('acc.txt','r',encoding='utf-8').read().splitlines()[0].split(';')[0])
   driver.find_element_by_name('password').send_keys(open('acc.txt','r',encoding='utf-8').read().splitlines()[0].split(';')[1])
   time.sleep(1)
   driver.find_element_by_name('password').send_keys(Keys.ENTER)


   # Đăng nhập bot số 2
   
   driver1 = webdriver.Chrome()
   driver1.maximize_window()
   driver1.get('https://discord.com/login')
   time.sleep(1)
   driver1.find_element_by_name('email').send_keys(open('acc.txt','r',encoding='utf-8').read().splitlines()[1].split(';')[0])
   driver1.find_element_by_name('password').send_keys(open('acc.txt','r',encoding='utf-8').read().splitlines()[1].split(';')[1])
   time.sleep(1)
   driver1.find_element_by_name('password').send_keys(Keys.ENTER)
   
   
   input('Đăng nhập xong bot')
   link_chanel = input('Link Channel Cần Spam (vd: https://discord.com/channels/959308519159504937/959340458369245204) : ')
   delay_time = int(input('Delay Reply Giữa Hai Bot: '))
   while True:
      try:
         data = open('data.txt','r',encoding='utf-8').read().splitlines()
         first_chat = data[0]
         


         driver.get(link_chanel)
         driver1.get(link_chanel)
         


         # Bot đầu tiên nhắn tin nhắn
         driver.find_element_by_xpath("/html/body/div[1]/div[2]/div/div[2]/div/div[1]/div/div/div[2]/div[2]/main/form/div/div/div/div[1]/div/div[3]/div/div[2]/div").send_keys(first_chat)
         time.sleep(1)
         m = driver.find_elements_by_xpath("//*[text()='"+first_chat+"']")
         m[len(m)-1].send_keys(Keys.ENTER)
         time.sleep(2)

         while True:

            if len(data) == 1:
               break
            # Bot thứ 2 rep lại tin nhắn
            ttt = driver1.find_elements_by_xpath("//*[text()='"+first_chat+"']")
            ttt = ttt[len(ttt)-1]
            actionChains = ActionChains(driver1)
            actionChains.context_click(ttt).perform()
            time.sleep(1)
            ttt = driver1.find_element_by_xpath("//*[text()='Trả lời']")
            ttt.click()
            time.sleep(delay_time)

            # Xóa tin nhắn đầu tiên
            data.remove(first_chat)
            first_chat = data[0]

            driver1.find_element_by_xpath('/html/body/div[1]/div[2]/div/div[2]/div/div[1]/div/div/div[2]/div[2]/main/form/div/div/div/div[2]/div/div[3]/div/div[2]').send_keys(first_chat)
            time.sleep(1)
            m = driver1.find_elements_by_xpath("//*[text()='"+first_chat+"']")
            m[len(m)-1].send_keys(Keys.ENTER)
            

            # Thời gian nghĩ giữa 2 nick
            time.sleep(2)

            
            if len(data) == 1:
               break
            ttt1 = driver.find_elements_by_xpath("//*[text()='"+first_chat+"']")
            ttt1 = ttt1[len(ttt1)-1]
            actionChains1 = ActionChains(driver)
            actionChains1.context_click(ttt1).perform()
            time.sleep(1)
            ttt1 = driver.find_element_by_xpath("//*[text()='Trả lời']")
            ttt1.click()
            time.sleep(delay_time)

            # Xóa tin nhắn đầu tiên
            data.remove(first_chat)
            first_chat = data[0]


            driver.find_element_by_xpath('/html/body/div[1]/div[2]/div/div[2]/div/div[1]/div/div/div[2]/div[2]/main/form/div/div/div/div[2]/div/div[3]/div/div[2]').send_keys(first_chat)
            time.sleep(1)
            m = driver.find_elements_by_xpath("//*[text()='"+first_chat+"']")
            m[len(m)-1].send_keys(Keys.ENTER)

            # Thời gian nghĩ giữa 2 nick
            time.sleep(2)
      except:
         pass

bot()




